/*
* Copyright (C) 2015 Dato, Inc.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU Affero General Public License as
* published by the Free Software Foundation, either version 3 of the
* License, or (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Affero General Public License for more details.
*
* You should have received a copy of the GNU Affero General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_graphlab_Updater */

#ifndef _Included_org_graphlab_Updater
#define _Included_org_graphlab_Updater
#ifdef __cplusplus
extern "C" {
#endif
#undef org_graphlab_Updater_IN_EDGES
#define org_graphlab_Updater_IN_EDGES 0L
#undef org_graphlab_Updater_OUT_EDGES
#define org_graphlab_Updater_OUT_EDGES 1L
#undef org_graphlab_Updater_ALL_EDGES
#define org_graphlab_Updater_ALL_EDGES 2L
#undef org_graphlab_Updater_NO_EDGES
#define org_graphlab_Updater_NO_EDGES 3L
#undef org_graphlab_Updater_NULL_CONSISTENCY
#define org_graphlab_Updater_NULL_CONSISTENCY 0L
#undef org_graphlab_Updater_VERTEX_CONSISTENCY
#define org_graphlab_Updater_VERTEX_CONSISTENCY 1L
#undef org_graphlab_Updater_EDGE_CONSISTENCY
#define org_graphlab_Updater_EDGE_CONSISTENCY 2L
#undef org_graphlab_Updater_FULL_CONSISTENCY
#define org_graphlab_Updater_FULL_CONSISTENCY 3L
#undef org_graphlab_Updater_DEFAULT_CONSISTENCY
#define org_graphlab_Updater_DEFAULT_CONSISTENCY 4L
/*
 * Class:     org_graphlab_Updater
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_graphlab_Updater_initNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
